export enum NotificationType {
    PROJECT_INVITATION = 'PROJECT_INVITATION',
    PROJECT_MEMBER_ADDED = 'PROJECT_MEMBER_ADDED',
    PROJECT_MEMBER_REMOVED = 'PROJECT_MEMBER_REMOVED',
    PROJECT_ROLE_CHANGED = 'PROJECT_ROLE_CHANGED',
    PROJECT_UPDATED = 'PROJECT_UPDATED',
    PROJECT_DELETED = 'PROJECT_DELETED',
    SYSTEM_ANNOUNCEMENT = 'SYSTEM_ANNOUNCEMENT',
}
